type Product {
  id: ID!
  name: String
  brand: String
  category: Category
  images: [String!]
  discount: Float
  originalPrice: Float
  discountedPrice: Float
  rating: Float
  ratingCount: Int
  sizes: [Size!]
  colors: [Color!]
  tags: [Tag!]
  reviews: [Review!]
}

type Category {
  id: Int!
  category: String
  products: [Product!]
}

type Size {
  id: Int!
  size: String
  products: [Product!]
}

type Color {
  id: Int!
  color: String
  products: [Product!]
}

type Tag {
  id: Int!
  tag: String
  products: [Product!]
}

enum ProductSort {
  id
  name
  discount
  originalPrice
  discountedPrice
  rating
  ratingCount
}

input ProductFilter {
  category: String
  color: String
  size: String
  tag: String
}
